version: "3.9"
services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    container_name: real-world-docker-frontend
    command: serve -s build -l 3000
    ports:
      - "3000:3000"
    restart: unless-stopped
    stdin_open: true
    tty: true

  api:
    build: api
    command: "npm run start"
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      HOST: 127.0.0.1
      MONGO_URL: mongodb://api_db:27017/my_db
    depends_on:
      - api_db
  api_db:
    image: "mongo:latest"
    volumes:
      - mongodb_api:/data/db
volumes:
  mongodb_api:
    
