version: "3.9"
services:
  nginx:
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/nginx.conf

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm start
    stdin_open: true 
    tty: true        
    environment:
      - CHOKIDAR_USEPOLLING=true
      - MY_VAR=true
    volumes:
      - './frontend:/usr/src/app'
      - '/app/node_modules'

  api:
    command: npm run dev
    volumes:
      - ./api/src:/usr/src/app/src

    

